### ISSUE TITLE
Creating custom alias leads to 404 error

### ISSUE THREAD

**Issue by gregforcey** [simple-login/mac-app#1]
Using the Safari extension in the latest version in both Big Sur and Catalina returns a 404 error when creating a custom alias. This happens when using a personal domain or one of the simplelogin domains. 

<img width="372" alt="Screen Shot 2021-03-31 at 7 45 57 AM" src="https://user-images.githubusercontent.com/1922423/113139795-92275b80-91f5-11eb-9e1c-3d9dade512cb.png">

Creating a random alias seems to work as expected.

**Comment by nguyenkims** [comment]
@gregforcey thanks for letting us know, this bug was due to the removal of some endpoints on the API. It should be fixed now :)
