### ISSUE TITLE
Safari browser extension not available?

### ISSUE THREAD

**Issue by wealthychef1** [simple-login/mac-app#7]
Hello, a browser extension would sure be handy.  When I try to download it, I get an error from the apple store.  Is this no longer supported?   Thank you.  
![2024-02-07 20 43 20 CleanShot Safari](https://github.com/simple-login/mac-app/assets/4825448/f27e203c-fd65-4cac-b6a3-d2b370c939e6)

**Comment by ntnhon** [comment]
Hello, we're working on integrating the [javascript extension](https://github.com/simple-login/browser-extension) to the macOS app. It's more feature complete and will be released soon.

**Comment by wealthychef1** [comment]
Thank you.  How can I follow progress on this?  Cheers!

**Comment by ntnhon** [comment]
You can watch [this PR](https://github.com/simple-login/mac-app/pull/9). I'll merge it when it passes our QA process as well as Apple's review.

**Comment by ntnhon** [comment]
The app is now available on the App Store: https://apps.apple.com/us/app/simplelogin/id6475835429

**Comment by wealthychef1** [comment]
Just installed and tested and it worked, much better experience now, thank you.
